# Generated by Django 3.2.5 on 2021-08-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('imageUrl', models.CharField(max_length=120)),
                ('miscimageUrl', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=400)),
                ('branddescription', models.CharField(max_length=200)),
            ],
        ),
    ]
